default:
  @just --list

bios:
  systemctl reboot --firmware-setup

changelogs:
  rpm-ostree db diff --changelogs


setup-flatpaks:
  #!/bin/bash
  echo 'Installing flatpaks from the ublue recipe ...'
  flatpaks=$(yq '.flatpaks[]' < /usr/etc/ublue-recipe.yml)
  for pkg in $flatpaks; do \
      echo "Installing: ${pkg}" && \
      flatpak install --user --noninteractive flathub $pkg; \
  done

setup-pwa:
  echo 'Giving browser permission to create PWAs (Progressive Web Apps)'
  # Add for your favorite chromium-based browser
  flatpak override --user --filesystem=~/.local/share/applications --filesystem=~/.local/share/icons com.microsoft.Edge

 
update:
  rpm-ostree update
  flatpak update -y
  distrobox upgrade -a
